language: node_js
node_js:
  - "0.10"

services:
  - mongodb
  - elasticsearch

before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -y update
  # Don't install packages which conflict with travis
  - sudo apt-get -y install `cut -d " " -f 1 config/packages | egrep -v "(^#|mongodb|elasticsearch|redis-server|bundler)"`
  - bundle install

before_script:
  - make css

notifications:
  irc:
    channels:
      - "irc.mysociety.org#popit"
    use_notice: true
    skip_join: true
